### ISSUE TITLE
error happen when run

### ISSUE THREAD

**Issue by bighawkin** [sebastian-gregoricchio/snHiC#1]
snakemake -s $HOME/software/snHiC-main/workflow/snHiC.snakefile --configfile ./snHiC_test/snHiC_test_data_config.yaml --cores 10
Building DAG of jobs...
MissingInputException in line 390 of $HOME/software/snHiC-main/workflow/snHiC.snakefile:
Missing input files for rule D_generate_restriction_file_and_get_chrSizes:
    output: temp_resctriction_bed_file.bed, temp_chrSizes_file.txt
    affected files:
        $HOME/TE/GCF_000003025.6_Sscrofa11.1_genomic.fna.fai

I use the run and get the error ,how to deal with it. thank for your help

**Comment by sebastian-gregoricchio** [comment]
Do you have a .fai file in the same folder where your fasta is?
If not you can generate it by:    `samtools faidx genome.fa`

Other actions that may help are:
- unzip the genome `gunzip genome.fa.gz`
- provide the full path to the genome in the config file (instead of using $HOME variable)


P.S: I also noticed that you using a .fna format file. The accepted format is fasta (usually .fa or .fa.gz)

**Comment by sebastian-gregoricchio** [comment]
I am going to close this issue. If you have any other question, feel free to open a new one.
